/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ERIKA-MOKLET
 */
public class TugasPratikum1 extends javax.swing.JFrame {

public class Pencarian_Sederhana_naik{
    {
        try {
        int[] DataArray={0,1,2,3,4,5,6,7,8,9,10};
        int i, NilaiX;
        boolean ketemu;

    System.out.println("");
    System.out.println("Program Pencarian Data Sederhana");
    System.out.println("================================");
    System.out.println("");
        
    //menampilkan nilai array
    for(i=0;i<11;i++)
    System.out.print(DataArray[i]+" ");
    System.out.print("");
    System.out.println("");
    // Masukan Data yang Di cari

    String 
    bilangan=JOptionPanshowInputDialog("Masukan nilai yang kamu cari??");

    NilaiX=Integer.parseInt(bilangan);
    System.out.println("");
    System.out.println("data yang di cari  adalah="+NilaiX);
    ketemu=false;
    for(i=0;i<11;i++)

{

    if(DataArray[i]==NilaiX)
    {
        ketemu=true;
        break;
    }
}

System.out.println("===============================");

    System.out.println("");
    if(ketemu==true)

    System.out.println("Data di temukan pada elemen ke"+(i+1));
    
    else
    System.out.println("Data tidak di temukan");
    System.out.println("~~~~~~~");

    System.out.println("");
    System.out.println("");
    System.out.println("");
    System.out.println("");

    System.exit(0);
    } catch(NullPointerException e){
    System.out.println("NPE");}
    }
}

    /**
     * Creates new form TugasPratikum1
     */
    public TugasPratikum1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasPratikum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasPratikum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasPratikum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasPratikum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasPratikum1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
